### ISSUE TITLE
rpiweatherd v.1.1 TODO List

### ISSUE THREAD

**Issue by ronen25** [ronen25/rpiweatherd#1]
TODO:
-------------------------------

Completed:
-------------------------------
- [x] Distinguish error codes between different parts of the application.
- [x] fetch first=..., lastest=... additions. This command will allow the user to fetch either the <code>N</code> latest entries, or the first (i.e. last) <code>N</code> entries.
This'll allow some more proper benchmarking.
- [x] Triggers - Whenever the daemon detects a certain temperature, or a certain temperature range, a program/script can be executed with ceratin parameters. This'll be stored inside a file called rpiwd-triggers.conf.
- [x] Wiki documentation for triggers.
- [x] Measurement unit will be in the resultant JSON
- [x] Resolve .pid file issues
- [x] If a config file already exists, rpiweatherd -g should ask whether to replace it or not.
- [x] Configuration parsing should quit if a required value is empty.
- [x] A blank configuration file will be generated on installation (e.g. rpiweatherd -g will be run).
- [x] Newly-generated configuration file will not have any "(null)" values, but instead have empty values.
- [x] Print only once every 5 querying attempts, instead of printing all attempts.
- [x] HTTP server ID string will be static (i.e. determined by version number only)
- [x] Git revision/branch name will be shown in the --version flag.
- [x] Foreground mode will write errors to stderr instead of syslog (create a unified logging method), and prevent the daemon from daemonizing.
- [x] Temperature should be stored in Celsius. Upon retrieval it should be converted, if that is necessary.
- [x] Getopt long options
- [x] Integrate ini.h and parson.h into the build tree, instead of using their repositories as submodules. This'll ease development and cloning alike.
- [x] Fix "adsung" typo in wiki
- [x] Raspberry Pi 3 support.

**Comment by ronen25** [comment]
Completed with merger of 1.1-dev.
I'll make some final preparations and tests, but this can be closed.
