### ISSUE TITLE
rpiweatherd v.1.2 TODO List

### ISSUE THREAD

**Issue by ronen25** [ronen25/rpiweatherd#5]
TODO:
---------------------------------------
- [ ] Fix the weird bug on non-Raspbian systems.
- [ ] Attempt to enhance the performance of the HTTP server
- [ ] RFC-ify HTTP server
- [ ] Create an "about" page with nice info.

Optional:
-------------------------------
- [ ] HTTP 2.0 support (maybe?)
- [ ] Use an already existing HTTP server (maybe some single header library?)

Completed:
------------------------------
- [ ] Project Logo (maybe?)
